// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBffIZEWAte3oC5ocXP7G-6R6w1XTEmZvo',
    appId: '1:900421773320:web:7f45ea66668406018409bd',
    messagingSenderId: '900421773320',
    projectId: 'studigo-9876e',
    authDomain: 'studigo-9876e.firebaseapp.com',
    storageBucket: 'studigo-9876e.firebasestorage.app',
    measurementId: 'G-LHFM7JQJNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADGkJdHRHf0jlSqs_cLT_SYdLtbN9rOXs',
    appId: '1:900421773320:android:34b988d07ffd431c8409bd',
    messagingSenderId: '900421773320',
    projectId: 'studigo-9876e',
    storageBucket: 'studigo-9876e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkSBYr7pJSPB29dXQSw5S3SkFYAQSLMBs',
    appId: '1:900421773320:ios:431cf8874c2f2cc68409bd',
    messagingSenderId: '900421773320',
    projectId: 'studigo-9876e',
    storageBucket: 'studigo-9876e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkSBYr7pJSPB29dXQSw5S3SkFYAQSLMBs',
    appId: '1:900421773320:ios:431cf8874c2f2cc68409bd',
    messagingSenderId: '900421773320',
    projectId: 'studigo-9876e',
    storageBucket: 'studigo-9876e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBffIZEWAte3oC5ocXP7G-6R6w1XTEmZvo',
    appId: '1:900421773320:web:7f45ea66668406018409bd',
    messagingSenderId: '900421773320',
    projectId: 'studigo-9876e',
    storageBucket: 'studigo-9876e.firebasestorage.app',
  );
}
